###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union


class TVShowFile(BaseModel):
    
    
    folder: str
    filename: str

class TVShowInfo(BaseModel):
    
    
    idx: int
    series_name: str
    season_number: Optional[int] = None
    special_name: Optional[str] = None
    episode_number: Optional[int] = None
